// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: gametitles/game_titles.proto

package gametitles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Platform int32

const (
	Platform_PLAYSTATION_5 Platform = 0
	Platform_PC            Platform = 1
	Platform_PLAYSTATION_4 Platform = 2
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLAYSTATION_5",
		1: "PC",
		2: "PLAYSTATION_4",
	}
	Platform_value = map[string]int32{
		"PLAYSTATION_5": 0,
		"PC":            1,
		"PLAYSTATION_4": 2,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_gametitles_game_titles_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_gametitles_game_titles_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_gametitles_game_titles_proto_rawDescGZIP(), []int{0}
}

type GameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *GameRequest) Reset() {
	*x = GameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gametitles_game_titles_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRequest) ProtoMessage() {}

func (x *GameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gametitles_game_titles_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRequest.ProtoReflect.Descriptor instead.
func (*GameRequest) Descriptor() ([]byte, []int) {
	return file_gametitles_game_titles_proto_rawDescGZIP(), []int{0}
}

func (x *GameRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GameStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string     `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Platforms []Platform `protobuf:"varint,2,rep,packed,name=platforms,proto3,enum=gametitles.Platform" json:"platforms,omitempty"`
}

func (x *GameStats) Reset() {
	*x = GameStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gametitles_game_titles_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStats) ProtoMessage() {}

func (x *GameStats) ProtoReflect() protoreflect.Message {
	mi := &file_gametitles_game_titles_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStats.ProtoReflect.Descriptor instead.
func (*GameStats) Descriptor() ([]byte, []int) {
	return file_gametitles_game_titles_proto_rawDescGZIP(), []int{1}
}

func (x *GameStats) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GameStats) GetPlatforms() []Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

var File_gametitles_game_titles_proto protoreflect.FileDescriptor

var file_gametitles_game_titles_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x67, 0x61, 0x6d, 0x65, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x67, 0x61, 0x6d, 0x65, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x0b, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22,
	0x55, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x09, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x2a, 0x38, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x4c, 0x41, 0x59, 0x53, 0x54, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x35, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x50, 0x43, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x50, 0x4c, 0x41, 0x59, 0x53, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x34, 0x10, 0x02,
	0x32, 0x49, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x73, 0x12, 0x3b,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x73, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22, 0x00, 0x42, 0x54, 0x0a, 0x1b, 0x69,
	0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x73, 0x42, 0x0f, 0x47, 0x61, 0x6d, 0x65,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x22, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x69, 0x63, 0x6b, 0x73, 0x63,
	0x68, 0x75, 0x62, 0x65, 0x72, 0x74, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gametitles_game_titles_proto_rawDescOnce sync.Once
	file_gametitles_game_titles_proto_rawDescData = file_gametitles_game_titles_proto_rawDesc
)

func file_gametitles_game_titles_proto_rawDescGZIP() []byte {
	file_gametitles_game_titles_proto_rawDescOnce.Do(func() {
		file_gametitles_game_titles_proto_rawDescData = protoimpl.X.CompressGZIP(file_gametitles_game_titles_proto_rawDescData)
	})
	return file_gametitles_game_titles_proto_rawDescData
}

var file_gametitles_game_titles_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gametitles_game_titles_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gametitles_game_titles_proto_goTypes = []interface{}{
	(Platform)(0),       // 0: gametitles.Platform
	(*GameRequest)(nil), // 1: gametitles.GameRequest
	(*GameStats)(nil),   // 2: gametitles.GameStats
}
var file_gametitles_game_titles_proto_depIdxs = []int32{
	0, // 0: gametitles.GameStats.platforms:type_name -> gametitles.Platform
	1, // 1: gametitles.GameTitles.GetGame:input_type -> gametitles.GameRequest
	2, // 2: gametitles.GameTitles.GetGame:output_type -> gametitles.GameStats
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gametitles_game_titles_proto_init() }
func file_gametitles_game_titles_proto_init() {
	if File_gametitles_game_titles_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gametitles_game_titles_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gametitles_game_titles_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gametitles_game_titles_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gametitles_game_titles_proto_goTypes,
		DependencyIndexes: file_gametitles_game_titles_proto_depIdxs,
		EnumInfos:         file_gametitles_game_titles_proto_enumTypes,
		MessageInfos:      file_gametitles_game_titles_proto_msgTypes,
	}.Build()
	File_gametitles_game_titles_proto = out.File
	file_gametitles_game_titles_proto_rawDesc = nil
	file_gametitles_game_titles_proto_goTypes = nil
	file_gametitles_game_titles_proto_depIdxs = nil
}
